from transformers import pipeline

def moderate():
    print("Definition:\n\Persistent feeling of sadness, emptiness, or a loss of interest in daily activities.\nAffects mood, cognition, and physical well-being.\n\nSymptoms:\nEmotional: Prolonged sadness, hopelessness, irritability.\nCognitive: Difficulty concentrating, negative thoughts, feelings of worthlessness.\nPhysical: Changes in appetite, sleep disturbances, fatigue.\n\nTreatment:\nTherapy: Cognitive-behavioral therapy (CBT), psychodynamic therapy.\nMedications: Antidepressants (SSRIs, SNRIs, tricyclics).\nElectroconvulsive Therapy (ECT): For severe cases not responsive to other treatments.\n\nSelf-Help at Different Levels:\nMild Depression: Establish a routine, engage in pleasurable activities.\nModerate Depression: Reach out to friends and family for support, consider self-help resources.\nSevere Depression: Seek professional help immediately, involve a mental health professional.\n\nWeekend Activities for Relief:\nOutdoor activities and exposure to natural light.\nEngage in hobbies or activities that bring joy.\nAttend social events, even in a small and supportive setting.\n\nLifestyle Recommendations:\nRegular exercise to boost mood and energy.\nHealthy and balanced nutrition.\nEnsure adequate sleep and establish a consistent sleep routine.\n\nConclusion:\nDepression is a complex condition, and a combination of therapy, medication, and lifestyle changes can be effective. Seeking professional help is crucial, and early intervention enhances the likelihood of successful management and recovery.")



def dangerous():
    print("Definition:\n\Persistent feeling of sadness, emptiness, or a loss of interest in daily activities.\nAffects mood, cognition, and physical well-being.\n\nSymptoms:\nEmotional: Prolonged sadness, hopelessness, irritability.\nCognitive: Difficulty concentrating, negative thoughts, feelings of worthlessness.\nPhysical: Changes in appetite, sleep disturbances, fatigue.\n\nTreatment:\nTherapy: Cognitive-behavioral therapy (CBT), psychodynamic therapy.\nMedications: Antidepressants (SSRIs, SNRIs, tricyclics).\nElectroconvulsive Therapy (ECT): For severe cases not responsive to other treatments.\n\nSelf-Help at Different Levels:\nMild Depression: Establish a routine, engage in pleasurable activities.\nModerate Depression: Reach out to friends and family for support, consider self-help resources.\nSevere Depression: Seek professional help immediately, involve a mental health professional.\n\nWeekend Activities for Relief:\nOutdoor activities and exposure to natural light.\nEngage in hobbies or activities that bring joy.\nAttend social events, even in a small and supportive setting.\n\nLifestyle Recommendations:\nRegular exercise to boost mood and energy.\nHealthy and balanced nutrition.\nEnsure adequate sleep and establish a consistent sleep routine.\n\nConclusion:\nDepression is a complex condition, and a combination of therapy, medication, and lifestyle changes can be effective. Seeking professional help is crucial, and early intervention enhances the likelihood of successful management and recovery.")


