


def moderate():
    print("Definition:\nEnduring patterns of behavior, cognition, and inner experience that deviate significantly from cultural expectations.\nImpacts personal and social functioning and often leads to distress for the individual or others.\n\nSymptoms:\nBorderline Personality Disorder (BPD): Unstable relationships, self-image, and impulsivity.\nNarcissistic Personality Disorder (NPD): Grandiosity, lack of empathy, need for admiration.\nObsessive-Compulsive Personality Disorder (OCPD): Perfectionism, rigidity, preoccupation with rules.\n\nTreatment:\nTherapy: Dialectical behavior therapy (DBT), cognitive-behavioral therapy (CBT).\nMedications: Antidepressants, mood stabilizers, antipsychotics (if applicable).\nGroup Therapy: Support and interpersonal skill development.\n\nSelf-Help at Different Levels:\nMild Personality Disorder: Self-awareness, journaling, explore coping mechanisms.\nModerate Personality Disorder: Engage in social activities, mindfulness practices.\nSevere Personality Disorder: Professional intervention is essential, collaborate with a treatment team.\n\nWeekend Activities for Relief:\nArtistic or creative pursuits as a form of expression.\nAttend support groups or community events.\nOutdoor activities to promote relaxation.\n\nLifestyle Recommendations:\nDevelop and maintain a structured routine.\nFoster positive relationships and communication skills.\nFocus on self-care practices, including adequate sleep and stress management.\n\nConclusion:\nAddressing personality disorders involves a combination of therapy, medication (if necessary), and lifestyle adjustments. Seeking professional guidance is crucial to understanding and managing these complex conditions effectively.")



def dangerous():
    print("Definition:\nEnduring patterns of behavior, cognition, and inner experience that deviate significantly from cultural expectations.\nImpacts personal and social functioning and often leads to distress for the individual or others.\n\nSymptoms:\nBorderline Personality Disorder (BPD): Unstable relationships, self-image, and impulsivity.\nNarcissistic Personality Disorder (NPD): Grandiosity, lack of empathy, need for admiration.\nObsessive-Compulsive Personality Disorder (OCPD): Perfectionism, rigidity, preoccupation with rules.\n\nTreatment:\nTherapy: Dialectical behavior therapy (DBT), cognitive-behavioral therapy (CBT).\nMedications: Antidepressants, mood stabilizers, antipsychotics (if applicable).\nGroup Therapy: Support and interpersonal skill development.\n\nSelf-Help at Different Levels:\nMild Personality Disorder: Self-awareness, journaling, explore coping mechanisms.\nModerate Personality Disorder: Engage in social activities, mindfulness practices.\nSevere Personality Disorder: Professional intervention is essential, collaborate with a treatment team.\n\nWeekend Activities for Relief:\nArtistic or creative pursuits as a form of expression.\nAttend support groups or community events.\nOutdoor activities to promote relaxation.\n\nLifestyle Recommendations:\nDevelop and maintain a structured routine.\nFoster positive relationships and communication skills.\nFocus on self-care practices, including adequate sleep and stress management.\n\nConclusion:\nAddressing personality disorders involves a combination of therapy, medication (if necessary), and lifestyle adjustments. Seeking professional guidance is crucial to understanding and managing these complex conditions effectively.")


