def moderate():
    print("Definition:\nA severe mental disorder characterized by disruptions in thinking, perception, emotions, and behavior.\nOften involves hallucinations, delusions, and impaired social functioning.\n\nSymptoms:\nPositive Symptoms: Hallucinations, delusions, disorganized thinking.\nNegative Symptoms: Social withdrawal, diminished emotional expression, reduced motivation.\nCognitive Symptoms: Impaired memory, attention, and executive function.\n\nTreatment:\nMedications: Antipsychotics (typical and atypical).\nTherapy: Cognitive-behavioral therapy (CBT), supportive therapy.\nHospitalization: For acute episodes or safety concerns.\n\nSelf-Help at Different Levels:\nMild Symptoms: Establish a routine, monitor stress levels.\nModerate Symptoms: Involve family or a support network, explore coping strategies.\nSevere Symptoms: Immediate professional intervention required, adhere to prescribed treatment.\n\nWeekend Activities for Relief:\nEngage in low-stress activities.\nAttend support groups or community events.\nEncourage participation in hobbies that promote relaxation.\n\nLifestyle Recommendations:\nEncourage regular exercise for overall well-being.\nEnsure a balanced and nutritious diet.\nSupportive and structured living environment.\n\nConclusion:\nSchizophrenia requires a comprehensive approach involving medication, therapy, and social support. Regular communication with healthcare professionals and adherence to treatment plans are essential for managing symptoms and improving overall quality of life.")



def dangerous():
    print("Definition:\nA severe mental disorder characterized by disruptions in thinking, perception, emotions, and behavior.\nOften involves hallucinations, delusions, and impaired social functioning.\n\nSymptoms:\nPositive Symptoms: Hallucinations, delusions, disorganized thinking.\nNegative Symptoms: Social withdrawal, diminished emotional expression, reduced motivation.\nCognitive Symptoms: Impaired memory, attention, and executive function.\n\nTreatment:\nMedications: Antipsychotics (typical and atypical).\nTherapy: Cognitive-behavioral therapy (CBT), supportive therapy.\nHospitalization: For acute episodes or safety concerns.\n\nSelf-Help at Different Levels:\nMild Symptoms: Establish a routine, monitor stress levels.\nModerate Symptoms: Involve family or a support network, explore coping strategies.\nSevere Symptoms: Immediate professional intervention required, adhere to prescribed treatment.\n\nWeekend Activities for Relief:\nEngage in low-stress activities.\nAttend support groups or community events.\nEncourage participation in hobbies that promote relaxation.\n\nLifestyle Recommendations:\nEncourage regular exercise for overall well-being.\nEnsure a balanced and nutritious diet.\nSupportive and structured living environment.\n\nConclusion:\nSchizophrenia requires a comprehensive approach involving medication, therapy, and social support. Regular communication with healthcare professionals and adherence to treatment plans are essential for managing symptoms and improving overall quality of life.")


